name: Node.js CI

# いつ実行するか（mainかjs-ci-practiceブランチにPushされた時、またはPRが作られた時）
on:
  push:
    branches: [ "main", "js-ci-practice" ]
  pull_request:

# 何を実行するか
jobs:
  build:
    runs-on: ubuntu-latest # 最新のUbuntu環境を借りて実行
    
    defaults:
      run:
        working-directory: ./ci-task

    steps:
    # 1. あなたのコードをGitHubから取得
    - uses: actions/checkout@v4

    # 2. Node.js環境（バージョン20）をセットアップ
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. 必要なパッケージ（Jestなど）をインストール
    - name: Install dependencies
      run: npm install

    # 4. テストを実行！！
    - name: Run tests
      run: npm test